//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSoket.API.Models.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserStockList
    {
        public int Id { get; set; }
        public Nullable<int> Userid { get; set; }
        public string Symbol { get; set; }
        public Nullable<int> Quntity { get; set; }
        public Nullable<decimal> BuyingPrice { get; set; }
    
        public virtual UserTable UserTable { get; set; }
    }
}
