//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSoket.API.Models.DbContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebSocketEntities : DbContext
    {
        public WebSocketEntities()
            : base("name=WebSocketEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EQUITY_L> EQUITY_L { get; set; }
        public virtual DbSet<UserStockList> UserStockList { get; set; }
        public virtual DbSet<UserTable> UserTable { get; set; }
    }
}
